services:
  OxidAcademy\ProductDataReader\DataReaderService:
    autowire: true
    public: true

  OxidAcademy\ProductDataReader\Command\DataReaderCommand:
    autowire: true
    tags:
    - { name: 'console.command' }
